name: CI

on: ["push", "pull_request"]

env:
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
    CI: true

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js 12.x
                uses: actions/setup-node@v1
                with:
                    node-version: 12.x

            -   name: Install dependencies, build, lint and test
                run: |
                    sudo apt update
                    sudo apt install chromium-browser -y
                    npm ci
                    npm run lint
                    npm run build
                    npm run test
